### ISSUE TITLE
fix security vulnerabilities

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/clashofclans-army#3]
How to do it:

1. run `npm install`, it will report the vulnerabilities;
2. run `npm audit` to view them;
3. run `npm audit fix` to fix them;
4. run `npm audit` to check if there are vulnerabilities left;
5. if there are vulnerabilities remaining, it will be necessary to fix them manually. run `npm audit` and follow the instructions;
6. run `npm run test` to check if the tests still pass.

**Comment by chgasparoto** [comment]
Here are the vulnerabilities reported by Github: https://github.com/chgasparoto/clashofclans-army/network/alerts

**Comment by aravindh-nagarajan** [comment]
I ll take this up

**Comment by sylvainDNS** [comment]
Let's take a look

**Comment by SimonHuet** [comment]
Done in #6

**Comment by chgasparoto** [comment]
closed by #4
