### ISSUE TITLE
Add Ice Golem to the army

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/clashofclans-army#7]
Add the string **Ice Golem** inside the file src/clashofclans-army.json

**Comment by chgasparoto** [comment]
are you still interested in implement it?

**Comment by maal26** [comment]
@chgasparoto  I opened a PR #13  related to this Issue.

If this issue is already assigned to another person, feel free to close my PR.

**Comment by chgasparoto** [comment]
@maal26 I'll wait for it until tomorrow, otherwise, I'm going to merge your PR 👍
