### ISSUE TITLE
Add Bat Spell to the army

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/clashofclans-army#8]
Add the string **Bat Spell** inside the file src/clashofclans-army.json

**Comment by eduaugustus** [comment]
Hi, I can do it!

**Comment by chgasparoto** [comment]
@eduaugustus it's already done. You can take the #7 if want to.

**Comment by chgasparoto** [comment]
closed by #9

**Comment by eduaugustus** [comment]
@chgasparoto sure, i go do it!

**Comment by chgasparoto** [comment]
@eduaugustus it seems #7 has been taken as well. I'll create a new issue and assign to you.
